load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_selfie",
    calculators = [
    "//mediapipe/graphs/selfie_segmentation:selfie_segmentation_gpu_deps_image"],
)
